# Base da imagem
FROM ubuntu:latest 

# O comando RUN serve para executar um comando na imagem
# Nesse caso abaixo, estamos atualizando repositórios de pacotes
RUN apt update -y 

# Abaixo, estamos atualizando os pacotes constantes na imagem
RUN apt install bind9 dnsutils -y

# Copia arquivo para dentro da imagem
COPY named.conf.local /etc/bind

COPY db.asa.br /etc/bind
COPY db.cliente1.br /etc/bind
# Todo container docker precisa de um ponto de entrada/execução para 
# manter o container em funcionamento
# ENTRYPOINT [ "executable" ]
# No caso abaixo, o serviço chamado named (bind) é executado em primeiro plano
EXPOSE 5353/tcp
EXPOSE 5353/udp

CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]